error-comment-404         : Comentario nao encontrado.
error-ticket-404          : Ticket nao encontrado.
error-ticket-priority     : Voce nao tem suporte prioritario.
error-user-404            : Conta nao encontrada.
error-user-activated      : Conta nao ativada.
error-user-confirmed      : Conta nao confirmada.
error-user-credentials    : Erro de credenciais.
error-user-email          : Email nao registrado no banco.
error-privileges          : Voce nao tem privilegios para essa operacao.
